/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cute_milkshake.glb 
Author: Felix Yadomi (https://sketchfab.com/felixyadomi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-milkshake-3ba52a41b4b248df953684861d9e7a20
Title: Cute milkshake
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export function CuteMilkshake(props) {
  const { nodes, materials } = useGLTF('/Models/cute_milkshake.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.043}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.glass} position={[0, 1.001, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.milk} position={[0, 1.001, 0]} scale={1} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.straw_1} position={[-0.031, 2.686, 0.277]} rotation={[0.414, 0, 0]} scale={[0.093, 0.11, 0.093]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.straw_2} position={[-0.033, 2.686, 0.278]} rotation={[0.414, 0, 0]} scale={[0.093, 0.11, 0.093]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.stars} position={[-0.861, 4.38, 0.287]} rotation={[-2.342, -0.105, 0.777]} scale={[-0.235, 0.235, 0.235]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.stars} position={[-0.774, 3.794, -0.849]} rotation={[-2.284, 0.338, 0.467]} scale={[-0.261, 0.261, 0.261]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.stars} position={[-1.064, 2.83, 1.599]} rotation={[-1.756, -0.038, 2.204]} scale={[-0.36, 0.36, 0.36]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.diamonds} position={[-0.216, 3.812, 1.412]} rotation={[0.845, 0.48, -0.365]} scale={0.264} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.hearth} position={[-1.956, 4.494, -0.934]} rotation={[-0.07, -0.081, -0.298]} scale={0.232} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.hearth} position={[-1.869, 1.036, 1.359]} rotation={[0.374, 0.073, -0.213]} scale={0.299} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/cute_milkshake.glb')
