/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lowpoly_milk.glb 
Author: beewee (https://sketchfab.com/beewee)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-milk-91492741c1fe4b5b80c89d8202664cd5
Title: Lowpoly Milk
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Milk(props) {
  const { nodes, materials } = useGLTF('/Models/lowpoly_milk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Models/lowpoly_milk.glb')
