/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Milk = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("/Models/lowpoly_milk.glb");
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.lambert5SG}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
});

useGLTF.preload("/Models/lowpoly_milk.glb");
